name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy check-lessons Function
        uses: yc-actions/yc-sls-function@v2.4.0
        with:
          yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
          folder-id: b1g4s4k8tj83buc1hdoq
          function-name: check-lessons
          runtime: nodejs16
          memory: 128Mb
          execution-timeout: 60
          entrypoint: src/check-lessons.handler
          service-account: aje38cdteqcfo55pe02h
          environment: |
            HOST=${{ secrets.HOST }}
          include: |
            ./src
            package.json

      - name: Deploy check-records Function
        uses: yc-actions/yc-sls-function@v2.4.0
        with:
          yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
          folder-id: b1g4s4k8tj83buc1hdoq
          function-name: check-records
          runtime: nodejs16
          memory: 128Mb
          execution-timeout: 60
          entrypoint: src/check-records.handler
          service-account: aje38cdteqcfo55pe02h
          environment: |
            HOST=${{ secrets.HOST }}
          include: |
            ./src
            package.json

      - name: Deploy check-subscriptions Function
        uses: yc-actions/yc-sls-function@v2.4.0
        with:
          yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
          folder-id: b1g4s4k8tj83buc1hdoq
          function-name: check-subscriptions
          runtime: nodejs16
          memory: 128Mb
          execution-timeout: 60
          entrypoint: src/check-subscriptions.handler
          service-account: aje38cdteqcfo55pe02h
          environment: |
            HOST=${{ secrets.HOST }}
          include: |
            ./src
            package.json

      - name: Deploy sync-calendar-managers Function
        uses: yc-actions/yc-sls-function@v2.4.0
        with:
          yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
          folder-id: b1g4s4k8tj83buc1hdoq
          function-name: sync-calendar-managers
          runtime: nodejs16
          memory: 128Mb
          execution-timeout: 60
          entrypoint: src/sync-calendar-managers.handler
          service-account: aje38cdteqcfo55pe02h
          environment: |
            HOST=${{ secrets.HOST }}
          include: |
            ./src
            package.json

      - name: Deploy sync-currencies Function
        uses: yc-actions/yc-sls-function@v2.4.0
        with:
          yc-sa-json-credentials: ${{secrets.YC_SA_JSON_CREDENTIALS}}
          folder-id: b1g4s4k8tj83buc1hdoq
          function-name: sync-currencies
          runtime: nodejs16
          memory: 128Mb
          execution-timeout: 60
          entrypoint: src/sync-currencies.handler
          service-account: aje38cdteqcfo55pe02h
          environment: |
            HOST=${{ secrets.HOST }}
          include: |
            ./src
            package.json
